name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
      - 'development'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Hemmeligheter
  - name: fullSha
    value: '$(Build.SourceVersion)'
  - name: imageName
    value: 'eu.gcr.io/prod-bip/ssb/dapla/klass-subsets-api'
  - name: repoName
    value: 'prod-bip/ssb/dapla/klass-subsets-api'

jobs:
  - job: buildTestDockerBuildDockerPush
    displayName: 'Test/build app and Dockerimage'
    steps:
      - task: DockerCompose@0
        displayName: Container registry login
        inputs:
          containerregistrytype: Container Registry
          dockerRegistryEndpoint: dockerHubOlved
      - task: DockerCompose@0
        displayName: 'Run integration test backend services'
        inputs:
          action: Run services
          containerregistrytype: Container Registry
          dockerRegistryEndpoint: dockerHubOlved
          dockerComposeFile: docker-compose.ci.build.yml
          projectName: $(Build.Repository.Name)
          qualifyImageNames: true
          buildImages: false
          abortOnContainerExit: true
          detached: true
      - task: Maven@3
        displayName: 'Maven install'
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          goals: 'install'
          options: '-DskipTests=true -Dmaven.javadoc.skip=true'
      # Build Docker image
      - task: Docker@2
        displayName: 'Docker build'
        inputs:
          repository: $(imageName)
          command: 'build'
          Dockerfile: 'Dockerfile'
          tags: |
            $(Build.SourceBranchName)-imagescan-$(fullSha)
      - task: Docker@2
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        displayName: 'Login to GCR'
        inputs:
          command: login
          containerRegistry: gcrServiceConnection
      - task: Docker@2
        displayName: 'Docker push'
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        inputs:
          containerRegistry: gcrServiceConnection
          repository: $(repoName)
          command: 'push'
          Dockerfile: 'Dockerfile'
          tags: |
            $(Build.SourceBranchName)-imagescan-$(fullSha)
