version: '3.7'

services:

  postgresdb-subsets:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres


