# Metrics related configurations
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: metrics
      exposure:
        include: prometheus,health,info,metrics, scheduledtasks, mappings, loggers, logfile, beans
    enabled-by-default: true


springdoc:
  api-docs:
    path: /api-docs

# Logging related configurations
logging.level.no.ssb.subsetsservice: DEBUG


# postgrsql connection configuration



